zsc2021: hahaha  i  am xxx qqq
my-profile:
  name: xiong哥
  email: 469712814@qq.com

#配置swaggerApi文档是否开启
swagger:
  enable: true


library:
  location: xixixix
  books:
    - name: 哈哈哈
      description: 哦哦哦哦哦哦哦哦哦哦 描述
server:
  port: 8088
spring:
  application:
    name: 001-TestSpringBoot
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SSA?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  host: 127.0.0.1
  port: 6379
  database: 0

